name: Tinybird - test - GCS

on:
  workflow_dispatch:

env:
  TINYBIRD_HOST: ${{ secrets.TINYBIRD_HOST }}
  TINYBIRD_TOKEN: ${{ secrets.TINYBIRD_TOKEN }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: sync datasource
        run: curl -X POST "https://api.tinybird.co/v0/datasources/raw_gcs_journal_delta/scheduling/runs" -H "Authorization: Bearer p.eyJ1IjogImQ2YTJkMjM5LTViNWUtNDFmYy1iYzk1LTQwZDM2NDQyOGQ3MyIsICJpZCI6ICJlNTg3ZDhhNi03NWM0LTRlYzMtYTgwYy02ODFiYmU5MzNjMzYiLCAiaG9zdCI6ICJldV9zaGFyZWQifQ.vrIS1WybcOuA5tchPE-I1NLki_EDLpGC8UtxqBNEJ9k"
